# Generated by Django 4.2.16 on 2026-08-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tapverify.apps.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('welfare', 'Welfare'), ('medical', 'Medical'), ('emergency', 'Emergency'), ('trip', 'Trip')], default='welfare', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due', models.DateTimeField()),
                ('rail', models.CharField(choices=[('sasapay', 'SasaPay Checkout link')], default='sasapay', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('member_code', models.CharField(db_index=True, default=tapverify.apps.core.models._gen_receipt_code, max_length=20, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('has_qr_card', models.BooleanField(default=False)),
                ('has_nfc_sticker', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('treasurer', 'Treasurer'), ('verifier', 'Verifier')], default='treasurer', max_length=20)),
                ('pin_code', models.CharField(default='0000', help_text='App login PIN', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('chama', 'Chama / Revenue Group'), ('church', 'Church / Religious'), ('event', 'Event / Conference'), ('delivery', 'Delivery / Logistics')], default='chama', max_length=20)),
                ('phone', models.CharField(help_text='Admin contact phone', max_length=15)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('paybill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('meeting_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_radius_meters', models.IntegerField(default=500)),
                ('plan', models.CharField(choices=[('free', 'Free — 50 members'), ('basic', 'Basic — Ksh 1,000/mo — 200 members'), ('pro', 'Pro — Ksh 3,000/mo — unlimited')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment_cash', 'Cash Payment Collected'), ('payment_mpesa', 'M-Pesa Payment Verified'), ('payment_till', 'Till Payment Matched'), ('attendance_only', 'Attendance / No Payment'), ('penalty', 'Late Payment / Penalty')], default='payment_cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='approved', max_length=20)),
                ('verification_method', models.CharField(choices=[('manual', 'Manual Selection'), ('qr_scan', 'QR Code Scan'), ('nfc_tap', 'NFC Sticker Tap'), ('mpesa_callback', 'M-Pesa Auto-Match'), ('ussd', 'USSD Check-in')], default='manual', max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, null=True)),
                ('receipt_token', models.CharField(db_index=True, default=tapverify.apps.core.models._gen_receipt_token, max_length=32, unique=True)),
                ('receipt_pin', models.CharField(default=tapverify.apps.core.models._gen_receipt_pin, max_length=4)),
                ('sms_status', models.CharField(default='pending', max_length=20)),
                ('sms_message_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.member')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='core.staff')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.workspace')),
            ],
            options={
                'db_table': 'verification_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(default='welfare', max_length=50)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_contributions', models.IntegerField(default=0)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='core.member')),
            ],
            options={
                'db_table': 'streak_records',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='PaymentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('created', 'CREATED'), ('notified', 'NOTIFIED'), ('pending', 'PENDING'), ('completed', 'COMPLETED'), ('verified', 'VERIFIED'), ('streak', 'STREAK'), ('badge', 'BADGE'), ('reward', 'REWARD'), ('archived', 'ARCHIVED')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rail', models.CharField(blank=True, default='', max_length=20)),
                ('txn_ref', models.CharField(blank=True, default='', max_length=100)),
                ('payment_token', models.CharField(blank=True, db_index=True, default='', help_text='Unique reference per member for SasaPay checkout', max_length=16, unique=True)),
                ('checkout_url', models.URLField(blank=True, default='', help_text='SasaPay checkout URL to share via WhatsApp')),
                ('provider_checkout_id', models.CharField(blank=True, default='', help_text='SasaPay CheckoutRequestID', max_length=100)),
                ('provider_tx_code', models.CharField(blank=True, default='', help_text='SasaPay TransactionCode from webhook', max_length=100)),
                ('sms_status', models.CharField(default='pending', max_length=20)),
                ('sms_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.collection')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tasks', to='core.member')),
            ],
            options={
                'db_table': 'payment_tasks',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('due_soon', '3 Days Before Due'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('meeting_day', 'Meeting Day Reminder')], max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField()),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.workspace')),
            ],
            options={
                'db_table': 'payment_reminders',
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=tapverify.apps.core.models._gen_payment_token, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rail_used', models.CharField(default='sasapay', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_link', to='core.verificationevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='core.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='core.workspace')),
            ],
            options={
                'db_table': 'payment_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push'), ('till', 'Till Payment'), ('paybill', 'Paybill Payment')], max_length=20)),
                ('mpesa_receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=50)),
                ('raw_callback', models.JSONField(default=dict)),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_txn', to='core.verificationevent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='core.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='core.workspace')),
            ],
            options={
                'db_table': 'mpesa_transactions',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='collection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['workspace', 'created_at'], name='verificatio_workspa_d97816_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['member', 'created_at'], name='verificatio_member__2ffd35_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['receipt_token'], name='verificatio_receipt_f45bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['status', 'created_at'], name='verificatio_status_19735b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streakrecord',
            unique_together={('member', 'collection_type')},
        ),
        migrations.AlterUniqueTogether(
            name='paymenttask',
            unique_together={('collection', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('workspace', 'phone')},
        ),
    ]
