# Generated by Django 4.2.16 on 2026-10-03 15:40

from django.db import migrations, models
import django.db.models.deletion
import tapverify.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payout_method', models.CharField(choices=[('till', 'Till Number'), ('paybill', 'Paybill'), ('personal', 'Personal Number'), ('bank', 'Bank Account')], max_length=10)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('paybill_account', models.CharField(blank=True, max_length=60)),
                ('personal_phone', models.CharField(blank=True, max_length=20)),
                ('bank_details', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('pay_code', models.CharField(default=tapverify.apps.core.models.new_pay_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('unpaid', 'Not paid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_method', models.CharField(blank=True, max_length=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_mismatch', models.BooleanField(default=False)),
                ('transaction_ref', models.CharField(blank=True, max_length=60)),
                ('reminders_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.collection')),
            ],
            options={
                'ordering': ['name', 'phone'],
                'unique_together': {('collection', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('auth_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60)),
                ('transaction_code', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], default='unmatched', max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.collection')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.secretary'),
        ),
    ]
