# Generated by Django 4.2.16 on 2026-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='group_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='secretary',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
