-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-dontwarn io.flutter.embedding.**
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class org.json.** { *; }
